"""`answers.yaml` — what you would type into an application form.

Curation, not observation (DESIGN.md §3.3), and the same contract as companies.yaml,
criteria.yaml and profile.yaml: human-authored, loaded strictly, never rewritten by a
nightly run. The two machine writes that do exist are both narrow and both explicit —
`work --task prefill` regenerates the trailing block of unanswered questions, and the
Settings tab writes an answer you typed. Neither ever touches a line you wrote.

    identity   the fields every application asks for, under their canonical names
    resume     a path on disk; the browser attaches it, so it must be a real file
    answers    everything else, keyed by a slug, with the question text as an alias

Strict in the same way `profile.py` and `criteria.py` are: an unknown top-level key, an
unknown identity field, a missing name or email, or a resume path that does not exist
all raise. A silently-defaulted answer would be typed into a real application.

`hash` plays exactly the role `Profile.prose_hash` plays for judging: it covers the
answers, so adding one invalidates the prefill plans that needed it and nothing else.
Editing a comment costs nothing.
"""

from __future__ import annotations

import hashlib
from dataclasses import dataclass, field
from pathlib import Path
from typing import Any, Optional

import yaml

_TOP_KEYS = {"identity", "resume", "cover_letter", "answers"}

# The identity fields an application form can ask for under a canonical name. Closed on
# purpose: a typo'd key here would silently never be filled in, and a form field left
# blank looks exactly like a form field we had no answer for.
IDENTITY_KEYS = (
    "first_name",
    "last_name",
    "preferred_name",
    "email",
    "phone",
    "location",
    "linkedin",
    "github",
    "website",
    "school",
    "degree",
    "graduation_date",
    "pronouns",
)

REQUIRED_IDENTITY = ("first_name", "last_name", "email")

# Everything after this line is regenerated from `prefill_gaps` on every prefill run.
# Anything you write above it is yours and is never touched.
GAP_MARKER = (
    "# ===== unanswered questions · regenerated by `jobtracker work --task prefill` ====="
)


def normalize_label(label: str) -> str:
    """Fold a form label to a comparison key.

    Lowercase, drop punctuation, collapse whitespace. Deliberately aggressive: a
    trailing asterisk marking a field required does not make it a different question.
    """
    kept = [c.lower() if c.isalnum() else " " for c in label]
    return " ".join("".join(kept).split())


def slugify(label: str) -> str:
    """A stable, readable key for a question we have not seen before."""
    words = normalize_label(label).split()
    return "_".join(words[:8]) or "question"


@dataclass(frozen=True)
class Answer:
    key: str
    value: str
    aliases: tuple[str, ...] = ()


@dataclass(frozen=True)
class Answers:
    identity: dict = field(default_factory=dict)
    answers: dict = field(default_factory=dict)  # key -> Answer
    resume: Optional[Path] = None
    cover_letter: Optional[Path] = None
    path: Optional[Path] = None

    # -- lookup ---------------------------------------------------------------------
    def get(self, key: str) -> Optional[str]:
        """The answer for a key, from either block. None if there is not one."""
        if key in self.identity:
            return self.identity[key]
        answer = self.answers.get(key)
        return answer.value if answer else None

    @property
    def by_alias(self) -> dict:
        """Normalized question text -> key, for every alias you have written down.

        This is what lets an answer you wrote once be recognized at a company that
        phrases the question the same way, with no model call.
        """
        out: dict = {}
        for answer in self.answers.values():
            for alias in answer.aliases:
                out[normalize_label(alias)] = answer.key
            out.setdefault(normalize_label(answer.key.replace("_", " ")), answer.key)
        return out

    @property
    def answerable(self) -> list[str]:
        """Every key that currently holds an answer. The model chooses from this list."""
        return sorted([*self.identity.keys(), *self.answers.keys()])

    @property
    def hash(self) -> str:
        """Covers the answers only — not comments, not the gap block.

        Same mechanism as `Profile.prose_hash`: a plan is an answer to "what do I know
        right now", so it stays valid until what we know changes.
        """
        parts = [f"{k}={v}" for k, v in sorted(self.identity.items())]
        parts += [f"{k}={a.value}" for k, a in sorted(self.answers.items())]
        parts.append(f"resume={self.resume.name if self.resume else ''}")
        return hashlib.sha256("\n".join(parts).encode()).hexdigest()[:16]


def load_answers(path: str | Path) -> Answers:
    """Parse and validate answers.yaml. Raises rather than defaulting."""
    path = Path(path)
    try:
        raw = yaml.safe_load(path.read_text()) or {}
    except yaml.YAMLError as exc:
        raise ValueError(f"{path} is not valid YAML: {exc}") from exc
    if not isinstance(raw, dict):
        raise ValueError(f"{path}: expected a mapping at the top level")

    unknown = set(raw) - _TOP_KEYS
    if unknown:
        raise ValueError(
            f"{path}: unknown key(s) {', '.join(sorted(unknown))}; "
            f"expected {', '.join(sorted(_TOP_KEYS))}"
        )

    identity_raw = raw.get("identity") or {}
    if not isinstance(identity_raw, dict):
        raise ValueError(f"{path}: 'identity' must be a mapping")
    unknown_identity = set(identity_raw) - set(IDENTITY_KEYS)
    if unknown_identity:
        raise ValueError(
            f"{path}: unknown identity field(s) {', '.join(sorted(unknown_identity))}; "
            f"expected {', '.join(IDENTITY_KEYS)}"
        )
    identity = {k: str(v) for k, v in identity_raw.items() if v not in (None, "")}
    missing = [k for k in REQUIRED_IDENTITY if not identity.get(k)]
    if missing:
        raise ValueError(f"{path}: identity is missing {', '.join(missing)}")

    answers: dict = {}
    answers_raw = raw.get("answers") or {}
    if not isinstance(answers_raw, dict):
        raise ValueError(f"{path}: 'answers' must be a mapping")
    for key, value in answers_raw.items():
        answers[str(key)] = _parse_answer(str(key), value, path)

    return Answers(
        identity=identity,
        answers=answers,
        resume=_resolve_file(raw.get("resume"), path, "resume"),
        cover_letter=_resolve_file(raw.get("cover_letter"), path, "cover_letter"),
        path=path,
    )


def _parse_answer(key: str, value: Any, path: Path) -> Answer:
    if isinstance(value, dict):
        unknown = set(value) - {"value", "aliases"}
        if unknown:
            raise ValueError(
                f"{path}: answer {key!r} has unknown key(s) {', '.join(sorted(unknown))}"
            )
        text = value.get("value")
        if text is None or str(text).strip() == "":
            raise ValueError(f"{path}: answer {key!r} has no value")
        aliases = value.get("aliases") or []
        if not isinstance(aliases, list):
            raise ValueError(f"{path}: answer {key!r} aliases must be a list")
        return Answer(key, str(text), tuple(str(a) for a in aliases))
    if value is None or str(value).strip() == "":
        raise ValueError(
            f"{path}: answer {key!r} is empty. Delete the key rather than leaving it "
            "blank — an empty answer is indistinguishable from a missing one, and this "
            "text goes into a real application."
        )
    return Answer(key, str(value))


def _resolve_file(value: Any, yaml_path: Path, label: str) -> Optional[Path]:
    """A path relative to answers.yaml, checked to exist.

    Checked at load rather than at fill time: discovering that the resume is missing
    while a browser sits on an open application form is the worst moment to find out.
    """
    if value in (None, ""):
        return None
    resolved = Path(str(value))
    if not resolved.is_absolute():
        resolved = (yaml_path.parent / resolved).resolve()
    if not resolved.is_file():
        raise ValueError(f"{yaml_path}: {label} {value!r} is not a file ({resolved})")
    return resolved


# -- the machine-managed tail ---------------------------------------------------------
def _ordered_gaps(gaps) -> list:
    """Generic questions first, then each company's own — the Settings page's order.

    Imported lazily because `tasks/prefill` imports this module: at module scope the two
    would be a cycle. It is one function call on a file write, so the cost is nothing and
    the alternative is a third definition of "generic" living here.
    """
    from .tasks.prefill import split_gaps

    generic, per_company = split_gaps(list(gaps))
    ordered = list(generic)
    for _, rows in per_company:
        ordered.extend(rows)
    return ordered


def render_gap_block(gaps) -> str:
    """The commented-out stubs for every question we cannot answer.

    Commented rather than live keys with empty values, because a live empty value would
    load as an answer and get typed into a form. You uncomment one, fill it in, and it
    becomes real — and the next prefill run stops listing it.

    Ordered the way the Settings page orders it: the questions many employers ask first,
    then each company's own. This block is a rendering of `prefill_gaps` and so is that
    page; two renderings of one table should not disagree about what to do first.
    """
    lines = [
        GAP_MARKER,
        "#",
        "# Uncomment a block, move it up into `answers:`, and fill in the value.",
        "# Everything below this line is rewritten on every prefill run; everything",
        "# above it is yours and is never touched.",
        "#",
        "# Most-asked first: answering one of those fills that field at every employer",
        "# that asks it, forever.",
        "#",
    ]
    if not gaps:
        lines.append("# (nothing outstanding)")
        return "\n".join(lines) + "\n"

    for gap in _ordered_gaps(gaps):
        options = gap["options"]
        lines.append("#")
        if gap["type"] == "file":
            # A file upload cannot be answered with text, so the stub must not look
            # like it can. It points at the two top-level keys that do take a path.
            lines.append(f"# {gap['question_key']}: a FILE upload — {gap['ask']!r}")
            lines.append("#   Set the top-level `resume:` or `cover_letter:` key to a")
            lines.append("#   path instead; there is nothing to write here.")
            lines.append(f"#   # asked by: {gap['seen_on']}")
            continue
        lines.append(f"# {gap['question_key']}:")
        lines.append('#   value: ""')
        lines.append(f"#   aliases: [{_quote(gap['ask'])}]")
        lines.append(f"#   # asked by: {gap['seen_on']}  ·  type: {gap['type']}")
        if options:
            lines.append(f"#   # one of: {options}")
    return "\n".join(lines) + "\n"


def rewrite_gaps(path: str | Path, gaps) -> None:
    """Replace the managed tail of answers.yaml. Never touches anything above it."""
    path = Path(path)
    text = path.read_text()
    head = text.split(GAP_MARKER)[0].rstrip("\n")
    path.write_text(f"{head}\n\n{render_gap_block(gaps)}")


def insert_answer(text: str, key: str, value: str, aliases=()) -> str:
    """Return `text` with `key` added to its `answers:` block.

    Text surgery rather than a YAML round trip, because a round trip would delete every
    comment in the file — including the gap stubs the user is working through and the
    explanatory header. The result is validated by `safewrite` before it replaces
    anything, so a malformed insertion is refused rather than saved.
    """
    entry = [f"  {key}:", f"    value: {_quote(value)}"]
    if aliases:
        entry.append(f"    aliases: [{', '.join(_quote(a) for a in aliases)}]")
    block = "\n".join(entry)

    lines = text.split("\n")
    for i, line in enumerate(lines):
        if line.rstrip() == "answers:":
            # Insert at the top of the block: newest answers are the ones you are
            # actively working on, and the file reads better with them in reach.
            return "\n".join(lines[: i + 1] + entry + lines[i + 1 :])

    # No answers block yet — add one above the managed tail.
    head, sep, tail = text.partition(GAP_MARKER)
    new_head = f"{head.rstrip()}\n\nanswers:\n{block}\n\n"
    return new_head + sep + tail


def upsert_identity(text: str, fields: dict) -> str:
    """Return `text` with `identity:` updated to hold `fields`.

    Text surgery for the same reason `insert_answer` is: a YAML round trip deletes every
    comment in the file, including the gap stubs you are working through.

    Three cases per key, and the middle one is the reason this is not a two-liner. The
    example file — and therefore most real ones — carries the optional identity fields
    *commented out* as documentation of what can go there. Answering one has to replace
    that line in place rather than adding a second entry above it, or the file grows a
    duplicate-looking key and the comment stops matching what is set.

    An empty value deletes the key rather than writing a blank. A blank identity value
    would load as an answer and get typed into a real application as the empty string,
    which looks exactly like a field we had no answer for.
    """
    unknown = set(fields) - set(IDENTITY_KEYS)
    if unknown:
        raise ValueError(
            f"unknown identity field(s) {', '.join(sorted(unknown))}; "
            f"expected {', '.join(IDENTITY_KEYS)}"
        )

    lines = text.split("\n")
    start, end = _block_bounds(lines, "identity:")
    if start is None:
        return _insert_identity_block(text, fields)

    # In canonical order, so a first save comes out reading like the example file rather
    # than in whatever order the form's fields happened to arrive.
    for key in IDENTITY_KEYS:
        if key not in fields:
            continue
        value = str(fields[key] or "").strip()
        entry = f"  {key}: {_quote(value)}"
        live = _find_key_line(lines, start, end, key, commented=False)
        stub = _find_key_line(lines, start, end, key, commented=True)

        if live is not None:
            if value:
                lines[live] = entry
            else:
                del lines[live]
                end -= 1
        elif value:
            # A commented stub is replaced where it stands, so the field keeps the
            # position and ordering the file's author gave it.
            if stub is not None:
                lines[stub] = entry
            else:
                at = _last_entry_line(lines, start, end) + 1
                lines.insert(at, entry)
                end += 1

    return "\n".join(lines)


def set_resume(text: str, filename: str) -> str:
    """Return `text` with the top-level `resume:` key pointing at `filename`.

    The path is written relative to answers.yaml, matching `_resolve_file`'s contract —
    the two files travel together, and an absolute path baked into the bank would break
    the moment it is read from inside a container.
    """
    entry = f"resume: {_quote('./' + filename.lstrip('./'))}"
    lines = text.split("\n")

    for i, line in enumerate(lines):
        stripped = line.strip()
        if stripped.startswith("resume:"):
            lines[i] = entry
            return "\n".join(lines)
        if stripped.startswith("# resume:"):
            lines[i] = entry
            return "\n".join(lines)

    # No key yet. Above the managed tail, and above `answers:` if there is one, so the
    # file keeps reading identity → resume → answers like the example does.
    head, sep, tail = text.partition(GAP_MARKER)
    anchor = head.find("\nanswers:")
    if anchor != -1:
        return head[:anchor] + f"\n{entry}\n" + head[anchor:] + sep + tail
    return f"{head.rstrip()}\n\n{entry}\n\n" + sep + tail


# The file written when there is no answer bank yet, so that saving your identity in the
# Settings tab is what creates one. It is deliberately NOT a copy of
# `answers.example.yaml`: that file carries Ada Lovelace's name, email and phone as
# documentation, and a bank that loads with someone else's identity in it is exactly the
# failure this module's strictness exists to prevent. What survives from the example is
# the prose — the part that tells you what the file is for.
STARTER = f'''# What you would type into an application form.
#
# GITIGNORED — it holds your name, email, phone, and whatever else an employer has
# asked for. `answers.example.yaml` is the tracked file that documents the shape.
#
# Created from the Settings tab, and safe to edit by hand. Two narrow machine writes
# exist and neither touches a line you wrote:
#
#   * `jobtracker work --task prefill` regenerates the block of unanswered questions at
#     the very end of the file.
#   * the Settings tab sets identity fields, the resume path, and answers you type there.
#
# Loaded strictly. An unknown key, an unknown identity field, a missing name or email,
# or a resume path that is not a real file all raise — a silently-defaulted answer would
# be typed into a real job application.

# The fields every application asks for, under their canonical names. first_name,
# last_name and email are required; the rest are filled when a form asks for them.
identity:

# A path, relative to this file. The browser attaches it with set_input_files() — the
# one thing no URL and no cookie can ever do. Checked at load, not at fill time.
# resume: ./resume.pdf

# Everything else, keyed by a slug. A plain string is the answer; the long form adds
# `aliases`, which are the exact question texts this answer covers. Aliases are what let
# an answer you wrote once be recognized at every company that phrases it the same way,
# with no model call at all.
answers:

{GAP_MARKER}
#
# (nothing outstanding)
'''


def _block_bounds(lines: list, header: str):
    """(index of `header`, index one past its block). (None, None) if absent.

    The block ends at the next line that starts in column zero and is not blank or a
    comment — i.e. the next top-level key. Comments inside the block belong to it.
    """
    start = None
    for i, line in enumerate(lines):
        if line.rstrip() == header:
            start = i
            break
    if start is None:
        return None, None

    for j in range(start + 1, len(lines)):
        line = lines[j]
        if not line.strip() or line.lstrip().startswith("#"):
            continue
        if line[:1] not in (" ", "\t"):
            return start, j
    return start, len(lines)


def _find_key_line(lines: list, start: int, end: int, key: str, commented: bool):
    """Index of `key`'s line inside a block, or None."""
    prefix = f"# {key}:" if commented else f"{key}:"
    alt = f"#{key}:" if commented else None
    for i in range(start + 1, end):
        stripped = lines[i].strip()
        if stripped.startswith(prefix) or (alt and stripped.startswith(alt)):
            return i
    return None


def _last_entry_line(lines: list, start: int, end: int) -> int:
    """Index of the last live entry in a block, or the header itself if it is empty.

    New keys go after it rather than at the top, which keeps them in canonical order —
    and, more importantly, keeps them from landing above a trailing comment that belongs
    to the *next* section. A freshly created `identity:` is followed by exactly that.
    """
    last = start
    for i in range(start + 1, end):
        stripped = lines[i].strip()
        if stripped and not stripped.startswith("#"):
            last = i
    return last


def _insert_identity_block(text: str, fields: dict) -> str:
    """Add an `identity:` block to a file that has none, above `answers:`."""
    entries = [
        f"  {k}: {_quote(str(v).strip())}"
        for k, v in fields.items()
        if str(v or "").strip()
    ]
    block = "identity:\n" + "\n".join(entries)

    head, sep, tail = text.partition(GAP_MARKER)
    anchor = head.find("\nanswers:")
    if anchor != -1:
        return head[:anchor] + f"\n{block}\n" + head[anchor:] + sep + tail
    return f"{head.rstrip()}\n\n{block}\n\n" + sep + tail


def _quote(value: str) -> str:
    """A YAML double-quoted scalar. Safe for colons, hashes, and newlines alike."""
    escaped = str(value).replace("\\", "\\\\").replace('"', '\\"').replace("\n", "\\n")
    return f'"{escaped}"'
