"""`answers.yaml` — what you would type into an application form.

Curation, not observation (DESIGN.md §3.3), and the same contract as companies.yaml,
criteria.yaml and profile.yaml: human-authored, loaded strictly, never rewritten by a
nightly run. The two machine writes that do exist are both narrow and both explicit —
`work --task prefill` regenerates the trailing block of unanswered questions, and the
Settings tab writes an answer you typed. Neither ever touches a line you wrote.

    identity   the fields every application asks for, under their canonical names
    resume     a path on disk; the browser attaches it, so it must be a real file
    answers    everything else, keyed by a slug, with the question text as an alias

Strict in the same way `profile.py` and `criteria.py` are: an unknown top-level key, an
unknown identity field, a missing name or email, or a resume path that does not exist
all raise. A silently-defaulted answer would be typed into a real application.

`hash` plays exactly the role `Profile.prose_hash` plays for judging: it covers the
answers, so adding one invalidates the prefill plans that needed it and nothing else.
Editing a comment costs nothing.
"""

from __future__ import annotations

import hashlib
from dataclasses import dataclass, field
from pathlib import Path
from typing import Any, Optional

import yaml

_TOP_KEYS = {"identity", "resume", "cover_letter", "answers"}

# The identity fields an application form can ask for under a canonical name. Closed on
# purpose: a typo'd key here would silently never be filled in, and a form field left
# blank looks exactly like a form field we had no answer for.
IDENTITY_KEYS = (
    "first_name",
    "last_name",
    "preferred_name",
    "email",
    "phone",
    "location",
    "linkedin",
    "github",
    "website",
    "school",
    "degree",
    "graduation_date",
    "pronouns",
)

REQUIRED_IDENTITY = ("first_name", "last_name", "email")

# Everything after this line is regenerated from `prefill_gaps` on every prefill run.
# Anything you write above it is yours and is never touched.
GAP_MARKER = (
    "# ===== unanswered questions · regenerated by `jobtracker work --task prefill` ====="
)


def normalize_label(label: str) -> str:
    """Fold a form label to a comparison key.

    Lowercase, drop punctuation, collapse whitespace. Deliberately aggressive: a
    trailing asterisk marking a field required does not make it a different question.
    """
    kept = [c.lower() if c.isalnum() else " " for c in label]
    return " ".join("".join(kept).split())


def slugify(label: str) -> str:
    """A stable, readable key for a question we have not seen before."""
    words = normalize_label(label).split()
    return "_".join(words[:8]) or "question"


@dataclass(frozen=True)
class Answer:
    key: str
    value: str
    aliases: tuple[str, ...] = ()


@dataclass(frozen=True)
class Answers:
    identity: dict = field(default_factory=dict)
    answers: dict = field(default_factory=dict)  # key -> Answer
    resume: Optional[Path] = None
    cover_letter: Optional[Path] = None
    path: Optional[Path] = None

    # -- lookup ---------------------------------------------------------------------
    def get(self, key: str) -> Optional[str]:
        """The answer for a key, from either block. None if there is not one."""
        if key in self.identity:
            return self.identity[key]
        answer = self.answers.get(key)
        return answer.value if answer else None

    @property
    def by_alias(self) -> dict:
        """Normalized question text -> key, for every alias you have written down.

        This is what lets an answer you wrote once be recognized at a company that
        phrases the question the same way, with no model call.
        """
        out: dict = {}
        for answer in self.answers.values():
            for alias in answer.aliases:
                out[normalize_label(alias)] = answer.key
            out.setdefault(normalize_label(answer.key.replace("_", " ")), answer.key)
        return out

    @property
    def answerable(self) -> list[str]:
        """Every key that currently holds an answer. The model chooses from this list."""
        return sorted([*self.identity.keys(), *self.answers.keys()])

    @property
    def hash(self) -> str:
        """Covers the answers only — not comments, not the gap block.

        Same mechanism as `Profile.prose_hash`: a plan is an answer to "what do I know
        right now", so it stays valid until what we know changes.
        """
        parts = [f"{k}={v}" for k, v in sorted(self.identity.items())]
        parts += [f"{k}={a.value}" for k, a in sorted(self.answers.items())]
        parts.append(f"resume={self.resume.name if self.resume else ''}")
        return hashlib.sha256("\n".join(parts).encode()).hexdigest()[:16]


def load_answers(path: str | Path) -> Answers:
    """Parse and validate answers.yaml. Raises rather than defaulting."""
    path = Path(path)
    try:
        raw = yaml.safe_load(path.read_text()) or {}
    except yaml.YAMLError as exc:
        raise ValueError(f"{path} is not valid YAML: {exc}") from exc
    if not isinstance(raw, dict):
        raise ValueError(f"{path}: expected a mapping at the top level")

    unknown = set(raw) - _TOP_KEYS
    if unknown:
        raise ValueError(
            f"{path}: unknown key(s) {', '.join(sorted(unknown))}; "
            f"expected {', '.join(sorted(_TOP_KEYS))}"
        )

    identity_raw = raw.get("identity") or {}
    if not isinstance(identity_raw, dict):
        raise ValueError(f"{path}: 'identity' must be a mapping")
    unknown_identity = set(identity_raw) - set(IDENTITY_KEYS)
    if unknown_identity:
        raise ValueError(
            f"{path}: unknown identity field(s) {', '.join(sorted(unknown_identity))}; "
            f"expected {', '.join(IDENTITY_KEYS)}"
        )
    identity = {k: str(v) for k, v in identity_raw.items() if v not in (None, "")}
    missing = [k for k in REQUIRED_IDENTITY if not identity.get(k)]
    if missing:
        raise ValueError(f"{path}: identity is missing {', '.join(missing)}")

    answers: dict = {}
    answers_raw = raw.get("answers") or {}
    if not isinstance(answers_raw, dict):
        raise ValueError(f"{path}: 'answers' must be a mapping")
    for key, value in answers_raw.items():
        answers[str(key)] = _parse_answer(str(key), value, path)

    return Answers(
        identity=identity,
        answers=answers,
        resume=_resolve_file(raw.get("resume"), path, "resume"),
        cover_letter=_resolve_file(raw.get("cover_letter"), path, "cover_letter"),
        path=path,
    )


def _parse_answer(key: str, value: Any, path: Path) -> Answer:
    if isinstance(value, dict):
        unknown = set(value) - {"value", "aliases"}
        if unknown:
            raise ValueError(
                f"{path}: answer {key!r} has unknown key(s) {', '.join(sorted(unknown))}"
            )
        text = value.get("value")
        if text is None or str(text).strip() == "":
            raise ValueError(f"{path}: answer {key!r} has no value")
        aliases = value.get("aliases") or []
        if not isinstance(aliases, list):
            raise ValueError(f"{path}: answer {key!r} aliases must be a list")
        return Answer(key, str(text), tuple(str(a) for a in aliases))
    if value is None or str(value).strip() == "":
        raise ValueError(
            f"{path}: answer {key!r} is empty. Delete the key rather than leaving it "
            "blank — an empty answer is indistinguishable from a missing one, and this "
            "text goes into a real application."
        )
    return Answer(key, str(value))


def _resolve_file(value: Any, yaml_path: Path, label: str) -> Optional[Path]:
    """A path relative to answers.yaml, checked to exist.

    Checked at load rather than at fill time: discovering that the resume is missing
    while a browser sits on an open application form is the worst moment to find out.
    """
    if value in (None, ""):
        return None
    resolved = Path(str(value))
    if not resolved.is_absolute():
        resolved = (yaml_path.parent / resolved).resolve()
    if not resolved.is_file():
        raise ValueError(f"{yaml_path}: {label} {value!r} is not a file ({resolved})")
    return resolved


# -- the machine-managed tail ---------------------------------------------------------
def render_gap_block(gaps) -> str:
    """The commented-out stubs for every question we cannot answer.

    Commented rather than live keys with empty values, because a live empty value would
    load as an answer and get typed into a form. You uncomment one, fill it in, and it
    becomes real — and the next prefill run stops listing it.
    """
    lines = [
        GAP_MARKER,
        "#",
        "# Uncomment a block, move it up into `answers:`, and fill in the value.",
        "# Everything below this line is rewritten on every prefill run; everything",
        "# above it is yours and is never touched.",
        "#",
    ]
    if not gaps:
        lines.append("# (nothing outstanding)")
        return "\n".join(lines) + "\n"

    for gap in gaps:
        options = gap["options"]
        lines.append("#")
        if gap["type"] == "file":
            # A file upload cannot be answered with text, so the stub must not look
            # like it can. It points at the two top-level keys that do take a path.
            lines.append(f"# {gap['question_key']}: a FILE upload — {gap['ask']!r}")
            lines.append("#   Set the top-level `resume:` or `cover_letter:` key to a")
            lines.append("#   path instead; there is nothing to write here.")
            lines.append(f"#   # asked by: {gap['seen_on']}")
            continue
        lines.append(f"# {gap['question_key']}:")
        lines.append('#   value: ""')
        lines.append(f"#   aliases: [{_quote(gap['ask'])}]")
        lines.append(f"#   # asked by: {gap['seen_on']}  ·  type: {gap['type']}")
        if options:
            lines.append(f"#   # one of: {options}")
    return "\n".join(lines) + "\n"


def rewrite_gaps(path: str | Path, gaps) -> None:
    """Replace the managed tail of answers.yaml. Never touches anything above it."""
    path = Path(path)
    text = path.read_text()
    head = text.split(GAP_MARKER)[0].rstrip("\n")
    path.write_text(f"{head}\n\n{render_gap_block(gaps)}")


def insert_answer(text: str, key: str, value: str, aliases=()) -> str:
    """Return `text` with `key` added to its `answers:` block.

    Text surgery rather than a YAML round trip, because a round trip would delete every
    comment in the file — including the gap stubs the user is working through and the
    explanatory header. The result is validated by `safewrite` before it replaces
    anything, so a malformed insertion is refused rather than saved.
    """
    entry = [f"  {key}:", f"    value: {_quote(value)}"]
    if aliases:
        entry.append(f"    aliases: [{', '.join(_quote(a) for a in aliases)}]")
    block = "\n".join(entry)

    lines = text.split("\n")
    for i, line in enumerate(lines):
        if line.rstrip() == "answers:":
            # Insert at the top of the block: newest answers are the ones you are
            # actively working on, and the file reads better with them in reach.
            return "\n".join(lines[: i + 1] + entry + lines[i + 1 :])

    # No answers block yet — add one above the managed tail.
    head, sep, tail = text.partition(GAP_MARKER)
    new_head = f"{head.rstrip()}\n\nanswers:\n{block}\n\n"
    return new_head + sep + tail


def _quote(value: str) -> str:
    """A YAML double-quoted scalar. Safe for colons, hashes, and newlines alike."""
    escaped = str(value).replace("\\", "\\\\").replace('"', '\\"').replace("\n", "\\n")
    return f'"{escaped}"'
